TEMPLATE = app
TARGET = QtNFSWTuningCalculator
QT += core \
    gui \
    network \
    xml
HEADERS += src/Widgets/XmlShardListReader.h \
    src/MsgDialogs.h \
    src/Settings/MnuBtnItems.h \
    src/Settings/MnuItems.h \
    src/Widgets/DlgCarImport.h \
    src/Widgets/DlgCode.h \
    src/Widgets/DlgSetLikelihood.h \
    src/Widgets/LstWdgCar.h \
    src/Widgets/ObjDownloader.h \
    src/Widgets/XmlCarListReader.h \
    src/Widgets/DlgInversion.h \
    src/Widgets/WdgCarItem.h \
    src/Widgets/DlgCarList.h \
    src/Classes/EAttribute.h \
    src/Classes/CAttributes.h \
    src/Classes/CBrand.h \
    src/Classes/CCar.h \
    src/Classes/CPart.h \
    src/Classes/CTuning.h \
    src/Classes/EClass.h \
    src/Classes/ESeries.h \
    src/Classes/EType.h \
    src/Classes/EValue.h \
    src/Classes/TypeDefinitions.h \
    src/Classes/TypeDefinitions.h \
    src/Menubar/MnbMenubar.h \
    src/Menubar/MnuBase.h \
    src/Menubar/MnuCar.h \
    src/Menubar/MnuFile.h \
    src/Menubar/MnuInfo.h \
    src/Parser/IniFile.h \
    src/Parser/IniParameter.h \
    src/Parser/IniParameters.h \
    src/Parser/IniSection.h \
    src/Parser/Parser.h \
    src/Parser/ParserFile.h \
    src/Settings/DlgSettings.h \
    src/Settings/WdgTabSettings.h \
    src/Statusbar/LabLikelihood.h \
    src/Statusbar/StbStatus.h \
    src/Tab/Attributes/WdgCarAttribute.h \
    src/Tab/Attributes/WdgCarAttributeBtn.h \
    src/Tab/Attributes/WdgCarAttributeBtns.h \
    src/Tab/Attributes/WdgCarAttributeLab.h \
    src/Tab/Attributes/WdgCarAttributeLabs.h \
    src/Tab/Attributes/WdgCarAttributeSpb.h \
    src/Tab/Attributes/WdgCarAttributeSpbs.h \
    src/Tab/Attributes/WdgCarAttributes.h \
    src/Tab/Car/ActCar.h \
    src/Tab/Car/MnuBtnCar.h \
    src/Tab/Car/MnuCars.h \
    src/Tab/Car/WdgCar.h \
    src/Tab/Menus/ActPart.h \
    src/Tab/Menus/ActPartClass.h \
    src/Tab/Menus/ActPartSeries.h \
    src/Tab/Menus/ActSolution.h \
    src/Tab/Menus/MnuAnalyzer.h \
    src/Tab/Menus/MnuMaximizer.h \
    src/Tab/Menus/MnuPartConstraints.h \
    src/Tab/Menus/MnuParts.h \
    src/Tab/Menus/MnuSolutions.h \
    src/Tab/Menus/MnuTab.h \
    src/Tab/Menus/MnuTabTrd.h \
    src/Tab/Menus/MnuTuner.h \
    src/Tab/Parts/WdgPart.h \
    src/Tab/Parts/WdgPartBtn.h \
    src/Tab/Parts/WdgPartBtns.h \
    src/Tab/Parts/WdgPartLab.h \
    src/Tab/Parts/WdgPartLabs.h \
    src/Tab/Parts/WdgPartPercent.h \
    src/Tab/Parts/WdgPartPercents.h \
    src/Tab/Parts/WdgParts.h \
    src/Tab/Threads/Trd.h \
    src/Tab/Threads/TrdAnalyze.h \
    src/Tab/Threads/TrdMaximize.h \
    src/Tab/WdgTab.h \
    src/Tab/WdgTabAnalyzer.h \
    src/Tab/WdgTabMaximizer.h \
    src/Tab/WdgTabTrd.h \
    src/Tab/WdgTabTuner.h \
    src/UndoRedo/UnReAttribute.h \
    src/UndoRedo/UnReAttributes.h \
    src/UndoRedo/UnReAttributesAndSolutions.h \
    src/UndoRedo/UnReCar.h \
    src/UndoRedo/UnReCarAndTuning.h \
    src/UndoRedo/UnReCarAttributesAndSolutions.h \
    src/UndoRedo/UnReClassConstraint.h \
    src/UndoRedo/UnReCmd.h \
    src/UndoRedo/UnRePart.h \
    src/UndoRedo/UnReSeriesConstraint.h \
    src/UndoRedo/UnReSolution.h \
    src/UndoRedo/UnReSolutions.h \
    src/UndoRedo/UnReStack.h \
    src/UndoRedo/UnReTuning.h \
    src/WdgCalculator.h \
    src/Widgets/DlgCarChooser.h \
    src/Widgets/DlgCompareDiagram.h \
    src/Widgets/DlgDiagram.h \
    src/Widgets/DlgTuningDiagram.h \
    src/Widgets/QSingleItemRatioLayout.h \
    src/Widgets/WdgHTRating.h \
    src/Widgets/WdgRating.h \
    src/Widgets/WdgVPRating.h \
    src/info.h \
    src/utils.h \
    src/WndCalculator.h
SOURCES += src/Widgets/XmlShardListReader.cpp \
    src/MsgDialogs.cpp \
    src/Settings/MnuBtnItems.cpp \
    src/Settings/MnuItems.cpp \
    src/Widgets/DlgCarImport.cpp \
    src/Widgets/DlgCode.cpp \
    src/Widgets/DlgSetLikelihood.cpp \
    src/Widgets/LstWdgCar.cpp \
    src/Widgets/ObjDownloader.cpp \
    src/Widgets/XmlCarListReader.cpp \
    src/Widgets/DlgInversion.cpp \
    src/Widgets/WdgCarItem.cpp \
    src/Widgets/DlgCarList.cpp \
    src/Classes/EAttribute.cpp \
    src/Classes/CAttributes.cpp \
    src/Classes/CBrand.cpp \
    src/Classes/CCar.cpp \
    src/Classes/CPart.cpp \
    src/Classes/CTuning.cpp \
    src/Classes/EClass.cpp \
    src/Classes/ESeries.cpp \
    src/Classes/EType.cpp \
    src/Menubar/MnbMenubar.cpp \
    src/Menubar/MnuBase.cpp \
    src/Menubar/MnuCar.cpp \
    src/Menubar/MnuFile.cpp \
    src/Menubar/MnuInfo.cpp \
    src/Parser/IniFile.cpp \
    src/Parser/IniParameter.cpp \
    src/Parser/IniParameters.cpp \
    src/Parser/IniSection.cpp \
    src/Parser/Parser.cpp \
    src/Parser/ParserFile.cpp \
    src/Settings/DlgSettings.cpp \
    src/Settings/WdgTabSettings.cpp \
    src/Statusbar/LabLikelihood.cpp \
    src/Statusbar/StbStatus.cpp \
    src/Tab/Attributes/WdgCarAttribute.cpp \
    src/Tab/Attributes/WdgCarAttributeBtn.cpp \
    src/Tab/Attributes/WdgCarAttributeBtns.cpp \
    src/Tab/Attributes/WdgCarAttributeLab.cpp \
    src/Tab/Attributes/WdgCarAttributeLabs.cpp \
    src/Tab/Attributes/WdgCarAttributeSpb.cpp \
    src/Tab/Attributes/WdgCarAttributeSpbs.cpp \
    src/Tab/Attributes/WdgCarAttributes.cpp \
    src/Tab/Car/ActCar.cpp \
    src/Tab/Car/MnuBtnCar.cpp \
    src/Tab/Car/MnuCars.cpp \
    src/Tab/Car/WdgCar.cpp \
    src/Tab/Menus/ActPart.cpp \
    src/Tab/Menus/ActPartClass.cpp \
    src/Tab/Menus/ActPartSeries.cpp \
    src/Tab/Menus/ActSolution.cpp \
    src/Tab/Menus/MnuAnalyzer.cpp \
    src/Tab/Menus/MnuMaximizer.cpp \
    src/Tab/Menus/MnuPartConstraints.cpp \
    src/Tab/Menus/MnuParts.cpp \
    src/Tab/Menus/MnuSolutions.cpp \
    src/Tab/Menus/MnuTab.cpp \
    src/Tab/Menus/MnuTabTrd.cpp \
    src/Tab/Menus/MnuTuner.cpp \
    src/Tab/Parts/WdgPart.cpp \
    src/Tab/Parts/WdgPartBtn.cpp \
    src/Tab/Parts/WdgPartBtns.cpp \
    src/Tab/Parts/WdgPartLab.cpp \
    src/Tab/Parts/WdgPartLabs.cpp \
    src/Tab/Parts/WdgPartPercent.cpp \
    src/Tab/Parts/WdgPartPercents.cpp \
    src/Tab/Parts/WdgParts.cpp \
    src/Tab/Threads/Trd.cpp \
    src/Tab/Threads/TrdAnalyze.cpp \
    src/Tab/Threads/TrdMaximize.cpp \
    src/Tab/WdgTab.cpp \
    src/Tab/WdgTabAnalyzer.cpp \
    src/Tab/WdgTabMaximizer.cpp \
    src/Tab/WdgTabTrd.cpp \
    src/Tab/WdgTabTuner.cpp \
    src/UndoRedo/UnReAttribute.cpp \
    src/UndoRedo/UnReAttributes.cpp \
    src/UndoRedo/UnReAttributesAndSolutions.cpp \
    src/UndoRedo/UnReCar.cpp \
    src/UndoRedo/UnReCarAndTuning.cpp \
    src/UndoRedo/UnReCarAttributesAndSolutions.cpp \
    src/UndoRedo/UnReClassConstraint.cpp \
    src/UndoRedo/UnReCmd.cpp \
    src/UndoRedo/UnRePart.cpp \
    src/UndoRedo/UnReSeriesConstraint.cpp \
    src/UndoRedo/UnReSolution.cpp \
    src/UndoRedo/UnReSolutions.cpp \
    src/UndoRedo/UnReStack.cpp \
    src/UndoRedo/UnReTuning.cpp \
    src/WdgCalculator.cpp \
    src/Widgets/DlgCarChooser.cpp \
    src/Widgets/DlgCompareDiagram.cpp \
    src/Widgets/DlgDiagram.cpp \
    src/Widgets/DlgTuningDiagram.cpp \
    src/Widgets/QSingleItemRatioLayout.cpp \
    src/Widgets/WdgHTRating.cpp \
    src/Widgets/WdgRating.cpp \
    src/Widgets/WdgVPRating.cpp \
    src/WndCalculator.cpp \
    src/utils.cpp \
    src/main.cpp
FORMS += 
RESOURCES += resource.qrc
RC_FILE = appicon.rc
TRANSLATIONS = untranslated.ts \
    german.ts \
    english.ts \
    spanish.ts
